// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GP_Achievement
{
        public const string achievement_clear_world_3 = "CgkIkM_-p6oUEAIQAw"; // <GPGSID>
        public const string achievement_clear_world_2 = "CgkIkM_-p6oUEAIQAg"; // <GPGSID>
        public const string achievement_clear_world_1 = "CgkIkM_-p6oUEAIQAQ"; // <GPGSID>
        public const string achievement_answer_question_in_30_sec = "CgkIkM_-p6oUEAIQBA"; // <GPGSID>
        public const string achievement_collect_30_star = "CgkIkM_-p6oUEAIQBw"; // <GPGSID>
        public const string achievement_answer_question_in_10_sec = "CgkIkM_-p6oUEAIQBQ"; // <GPGSID>
        public const string achievement_first_use_power_up = "CgkIkM_-p6oUEAIQBg"; // <GPGSID>
        public const string achievement_new_player = "CgkIkM_-p6oUEAIQAA"; // <GPGSID>
        public const string achievement_collect_60_star = "CgkIkM_-p6oUEAIQCA"; // <GPGSID>

}

